### ISSUE TITLE
liPGN broken with Java 9 update

### ISSUE THREAD

**Issue by lukhas** [s-ted/liPng#9]
$ java -version
    openjdk version "9.0.4"
    OpenJDK Runtime Environment (build 9.0.4+12-Debian-2)
    OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-2, mixed mode)

After removing all my local leiningen install to be sure, I did a "lein uberjar" which succeeded, but then lipgn fails:

```
$ java -jar target/liPGN.jar --user-agent "liPGN-lukhas" -p classical,rapid,blitz,unlimited -c white -u lukhas
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.orientechnologies.common.profiler.OProfilerStub.<init>(OProfilerStub.java:38)
        at com.orientechnologies.orient.core.Orient.startup(Orient.java:199)
        at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:87)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:52)
        at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:47)
        at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:37)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:130)
        at fr.tedoldi.lichess.game.retriever.orientdb.Dal.init(orientdb.clj:409)
        at fr.tedoldi.lichess.game.retriever.core$export_BANG_.invokeStatic(core.clj:47)
        at fr.tedoldi.lichess.game.retriever.core$export_BANG_.invoke(core.clj:31)
        at fr.tedoldi.lichess.game.retriever.main$run.invokeStatic(main.clj:60)
        at fr.tedoldi.lichess.game.retriever.main$run.invoke(main.clj:59)
        at fr.tedoldi.lichess.game.retriever.main$_main.invokeStatic(main.clj:84)
        at fr.tedoldi.lichess.game.retriever.main$_main.doInvoke(main.clj:69)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at fr.tedoldi.lichess.game.retriever.main.main(Unknown Source)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @44b940a2
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfigDiskCacheSize(OGlobalConfiguration.java:775)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfig(OGlobalConfiguration.java:757)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.<clinit>(OGlobalConfiguration.java:660)
        ... 16 more
```

**Comment by s-ted** [comment]
Java 9 needs leiningen 2.8.0+ to work correctly.

Will introduce the following Warnings at compilation and run time :

```
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clostache.parser, being replaced by: #'clojure.core.incubator/seqable?
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/home/ted/dev/liPGN/target/liPGN.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Will need orientdb 3.0 to be stable for their removal (orientechnologies/orientdb#7780)

**Comment by lukhas** [comment]
Yup it's working fine, with the warnings at runtime.
